theme: jekyll-theme-minimal
title: DDPS Sentiment analysis and its transition during the Palestine-Israelian conflict
description: Welcome to the website of a project ran by Johanna, Julia, and Tatsu!
Table of contents: 
Introduction
Timeline of the conflict
Summary
Research question 
Data
Methodology
Analysis
Limitation and further analysis
Conclusion
