theme: jekyll-theme-cayman
title: Framing the Israel-Palestine Conflict- A critical Analysis of Western media coverage in May 2021
description: Welcome to the website of a project ran by Johanna, Julia, and Tatsu!
Table of contents: 
Introduction
Timeline of the conflict
Summary
Research question 
Data
Methodology
Analysis
Limitation and further analysis
Conclusion
